version: '3'

services:
  hackathon-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development # Set to development for hot-reloading
    command: ['yarn', 'dev']
    volumes:
      - .:/app # Mount the local directory to /app in the container
